name: CI Style Checks

on:
  push:
    branches:
      - main
      - dev*
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  style:
    name: Style Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Pre-install
        run: |
          sudo apt-get update
          sudo apt-get -y -q install ffmpeg libavcodec-extra

      - name: Install the project
        run: uv sync --all-extras

      - name: pycodestyle
        run: pycodestyle --ignore=C0330,C0415,E203,E231,W503 --max-line-length=120 whisper_tiktok

      - name: pylint
        run: pylint --fail-under=9.6 whisper_tiktok

      - name: mypy
        run: mypy whisper_tiktok

      - name: ruff
        run: ruff check whisper_tiktok tests/

      - name: black
        run: |
          black --line-length 120 --check whisper_tiktok
          black --line-length 120 --check tests/
